[package]
name = "pgprofile"
version = "0.1.0"
edition = "2021"
license = "PostgreSQL"
repository = "https://github.com/k-jingyang/pgprofile"

[[bin]]
name = "pgprofile"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
postgres = "0.19"
humantime = "2"
ctrlc = "3"
comfy-table = "7"
crossterm = "0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
